### ISSUE TITLE
Filelist doesn't return any files

### ISSUE THREAD

**Issue by catalin13** [elgatito/script.elementum.burst#167]
Filelist recently changed their indexing/search and some of the API and whenever we search for something, we don't get any results/files from Filelist.
Quote from Filelist's Page:

"Torrents are now indexed in real time. Meaning that you can find it via search right after it's uploaded;
 We made some improvements to the way words are analyzed for indexing. To be more specific the search will now return much more accurate results;
 We have also greatly improved the algorithm which handles word positioning in the search engine, you can now find much shorter words and the relevance of the results is higher;

Let's go on with a short list of 'good-to-know' things for the API:

 You can find the API at: https://filelist.ro/api.php ;
 A 150 requests/hour/user limit is enforced;
 All API calls have to be sent as a GET request;
 The authentication is made using your username and passkey;
 The API can return responses as JSON as well as XML;
 At this moment there are two endpoints: search-torrents and latest-torrents;
 latest-torrents works the same way as the current RSS feed with the added benefit of being able to filter by IMDb;"

**Comment by arlekyn2** [comment]
Also coming in for the exact same issue. First of all, I should mention I'm not a coder/programmer, just an amateur user. So far I tried creating a new script for filelist api by simply using the rarbg one and changing the relevant data (base url... etc). In the end I came up with this:
"Filelist": {
        "anime_extra": null,
        "anime_keywords": "{title:original} {episode}",
        "anime_query": "?username=XXX&passkey=XXX&action=search-torrents&type=name&query=QUERY",
        "api_format": {
            "results": "",
            "name": "name",
            "peers": "leechers",
            "seeds": "seeders",
            "size": "size",
            "torrent": "download_link"
        },
        "base_url": "https://filelist.ro/api.php",
        "color": "FF3860BB",
        "enabled": true,
        "general_extra": null,
        "general_keywords": "{title:original}",
        "general_query": "?username=XXX&passkey=XXX&action=search-torrents&type=name&query=QUERY",
        "is_api": true,
        "language": null,
        "languages": "en, ro",
        "login_failed": "",
        "login_object": "",
        "login_path": null,
        "movie_extra": null,
        "movie_keywords": "{title:original} {year}",
        "movie_query": "?username=XXX&passkey=XXX&action=search-torrents&type=name&query=QUERY",
        "name": "FILELIST",
        "parser": {
            "infohash": null,
            "name": null,
            "peers": null,
            "seeds": null,
            "row": null,
            "size": null,
            "torrent": null
        },
        "predefined": true,
        "private": false,
        "season_extra": null,
        "season_extra2": null,
        "season_keywords": "{title:original} s{season:2}",
        "season_keywords2": null,
        "season_query": "?username=XXX&passkey=XXX&action=search-torrents&type=name&query=QUERY",
        "separator": "+",
        "show_query": "?username=XXX&passkey=XXX&action=search-torrents&type=name&query=QUERY",
        "subpage": null,
        "tv_extra": null,
        "tv_extra2": null,
        "tv_keywords": "{title:original} s{season:2}e{episode:2}",
        "tv_keywords2": "{title:original} {season:2}x01|S{season:2}",
        "tv_keywords_fallback": "{title:original} s{season:2}"
    },

The problem is the script doesn't return any result in elementum. My (non educated) guess is the part with "api_format" is not done properly.
Checking kodi logs I can see the query going to filelist is actually correct and it will return results in browser. These are kodi logs with the lack of results:


2020-01-24 09:48:35.399 T:3436180288  NOTICE: [script.elementum.burst] Loading definitions took 0.029200s
2020-01-24 09:48:35.450 T:3436180288  NOTICE: [script.elementum.burst] Burstin' with FILELISTNEW
2020-01-24 09:48:35.532 T:3427787584  NOTICE: [script.elementum.burst] [FilelistNew] Using translated 'original' title u'gotham'
2020-01-24 09:48:35.535 T:3427787584  NOTICE: [script.elementum.burst] >          FILELISTNEW search URL: https://filelist.ro/api.php?username=XXX&passkey=XXX&action=search-torrents&type=name&query=gotham+s02e13
2020-01-24 09:48:36.253 T:3916485440  NOTICE: [plugin.video.elementum] [36mDEBU  proxy        ▶ dumpRequest      [0m[6] --> GET https://filelist.ro:443/api.php?username=XXX&passkey=XXX&action=search-torrents&type=name&query=gotham+s02e13
2020-01-24 09:48:36.765 T:3916485440  NOTICE: [plugin.video.elementum] [36mDEBU  proxy        ▶ dumpResponse     [0m[6] <-- 404 https://filelist.ro:443/api.php?username=XXX&passkey=XXX&action=search-torrents&type=name&query=gotham+s02e13
2020-01-24 09:48:36.799 T:3427787584  NOTICE: [script.elementum.burst] [FilelistNew] Using translated 'original' title u'gotham'
2020-01-24 09:48:36.804 T:3427787584  NOTICE: [script.elementum.burst] >          FILELISTNEW search URL: https://filelist.ro/api.php?username=XXX&passkey=XXX&action=search-torrents&type=name&query=gotham+02x01%7CS02
2020-01-24 09:48:37.755 T:3916485440  NOTICE: [plugin.video.elementum] [36mDEBU  proxy        ▶ dumpRequest      [0m[8] --> GET https://filelist.ro:443/api.php?username=XXX&passkey=XXX&action=search-torrents&type=name&query=gotham+02x01%7CS02
2020-01-24 09:48:43.331 T:3916485440  NOTICE: [plugin.video.elementum] [GIN] 2020/01/24 - 07:48:43 | 200 | 12.073416622s |       127.0.0.1 | GET      /movies/trakt/trending?reload=20200124072817&doresume=false
2020-01-24 09:48:43.480 T:3371156288   ERROR: NEWADDON Unknown Video Info Key "dbtype"
2020-01-24 09:48:47.899 T:3916485440   ERROR: Previous line repeats 49 times.
2020-01-24 09:48:47.899 T:3916485440  NOTICE: [plugin.video.elementum] [36mDEBU  proxy        ▶ dumpResponse     [0m[8] <-- 404 https://filelist.ro:443/api.php?username=XXX&passkey=XXX&action=search-torrents&type=name&query=gotham+02x01%7CS02
2020-01-24 09:48:47.921 T:3427787584  NOTICE: [script.elementum.burst] [FilelistNew] Using translated 'original' title u'gotham'
2020-01-24 09:48:47.928 T:3427787584  NOTICE: [script.elementum.burst] >          FILELISTNEW search URL: https://filelist.ro/api.php?username=XXX&passkey=XXX&action=search-torrents&type=name&query=gotham+s02
2020-01-24 09:48:48.875 T:3916485440  NOTICE: [plugin.video.elementum] [36mDEBU  proxy        ▶ dumpRequest      [0m[10] --> GET https://filelist.ro:443/api.php?username=XXX&passkey=XXX&action=search-torrents&type=name&query=gotham+s02
2020-01-24 09:48:49.055 T:3916485440  NOTICE: [plugin.video.elementum] [36mDEBU  proxy        ▶ dumpResponse     [0m[10] <-- 200 https://filelist.ro:443/api.php?username=XXX&passkey=XXX&action=search-torrents&type=name&query=gotham+s02
2020-01-24 09:48:49.084 T:3427787584  NOTICE: [script.elementum.burst] >>         FILELISTNEW returned  0 results in 13.6 seconds
2020-01-24 09:48:49.190 T:3436180288  NOTICE: [script.elementum.burst] Providers returned 0 results in 13.75 seconds


And these are actually the results I get when using the query directly in the browser:

[{"id":426698,"name":"Gotham.S02.1080p.WEB-DL.DD5.1.H.264-NTb","imdb":"tt3749900","freeleech":1,"upload_date":"2016-05-24 18:01:22","download_link":"https:\/\/filelist.ro\/download.php?id=426698&passkey=XXX","size":38602794463,"internal":0,"moderated":1,"category":"Seriale HD","seeders":7,"leechers":0,"times_completed":1125,"comments":1,"files":22,"small_description":"Crime | Drama | Mystery"},{"id":426660,"name":"Gotham.S02.1080p.HDTV.DD5.1.X264-DIMENSION","imdb":"tt3749900","freeleech":1,"upload_date":"2016-05-24 14:30:49","download_link":"https:\/\/filelist.ro\/download.php?id=426660&passkey=XXX","size":46425820953,"internal":0,"moderated":1,"category":"Seriale HD","seeders":4,"leechers":0,"times_completed":1264,"comments":2,"files":22,"small_description":"Crime, Drama, Mystery"},{"id":426623,"name":"Gotham.S02.HDTV.x264-Scene","imdb":"tt3749900","freeleech":0,"upload_date":"2016-05-24 09:04:59","download_link":"https:\/\/filelist.ro\/download.php?id=426623&passkey=XXX","size":5460356284,"internal":0,"moderated":1,"category":"Seriale SD","seeders":17,"leechers":3,"times_completed":8206,"comments":6,"files":22,"small_description":"Crime, Drama, Thriller"},{"id":426596,"name":"Gotham.S02.720p.HDTV.X264-Scene","imdb":"tt3749900","freeleech":1,"upload_date":"2016-05-24 05:24:16","download_link":"https:\/\/filelist.ro\/download.php?id=426596&passkey=XXX","size":18358116401,"internal":0,"moderated":1,"category":"Seriale HD","seeders":16,"leechers":2,"times_completed":7593,"comments":5,"files":22,"small_description":"Action | Crime | Drama"}]

So if anyone could help fixing the script, that would be much appreciated!

**Comment by shmizan** [comment]
@arlekyn2 you were almost right in your script.
the problem is that filelist's API does not include the required header for the results.
the response is flawed, and so when you wrote "results": "", you referred the rest of the burst script to an empty array, and no results were returned.

a very hacky workaround I did is edit your provider as follows:

		"api_format": {
			"name": "name",
			"peers": "leechers",
			"results": "torrent_results",
			"seeds": "seeders",
			"size": "size",
			"torrent": "download_link"
		},

and edit burst.py as follows:

def extract_from_api(provider, client):
    """ Main API parsing generator for API-based providers

    An almost clever API parser, mostly just for YTS, RARBG and T411

    Args:
        provider  (str): Provider ID
        client (Client): Client class instance

    Yields:
        tuple: A torrent result
    """
    if provider.lower() == "filelist":
        json_answer = '{"torrent_results":' + client.content + '}'
    else:
        json_answer = client.content
    try:
        data = json.loads(json_answer)
    except:
        data = []
	log.debug("[%s] JSON response from API: %s" % (unquote(provider), repr(data)))

e.g. wrapping filelist's api response with a required array name, and then referring to it in providers.json
to really solve the problem we need to ask filelist's team to change the API to include the needed headers.

**Comment by arlekyn2** [comment]
Thanks for your input! I tried adding those lines of code, but burst threw back an error:

(PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndentationError'>
                                            Error Contents: expected an indented block (burst.py, line 410)
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/script.elementum.burst/burst.py", line 7, in <module>
                                                from burst.burst import search
                                              File "/storage/.kodi/addons/script.elementum.burst/burst/burst.py", line 410
                                                json_answer = '{"torrent_results":' + client.content + '}'
                                                          ^
                                            IndentationError: expected an indented block
                                            -->End of Python script error report<--

Any idea if i did something wrong or missed anything?

**Comment by shmizan** [comment]
it's just a simple indentation issue.. try to fix it, or follow how it's written in the file I've changed:
https://pastebin.com/YK9as6GG - the change starts from line 409.

**Comment by arlekyn2** [comment]
Thanks a lot for your help! It now works!

**Comment by elgatito** [comment]
I can include required changes in case proper pull request is added.

**Comment by elgatito** [comment]
I can include changes for Filelist if someone creates Pull Request.
I cannot even find information about API and cannot login there as well.

**Comment by arlekyn2** [comment]
Hi,
FileList API info: https://filelist.ro/forums.php?action=viewtopic&topicid=120435
It's not a very detailed description. However, I have no idea how to make a pull request. Also, please note that FL api requires a passkey instead of the regular password (which is found under user profile on FL website)... So it would require more work to also change the UI, not just the script.
Anyways,, I just edited the file directly through SSH to make it work (with the help I got from shmizan)

**Comment by elgatito** [comment]
@arlekyn2 to see that url - you need to be authorized.

**Comment by catalin13** [comment]
@elgatito I can give you a Filelist invite, please let me know how I could send this you you.

**Comment by Jezze83** [comment]
For now filelist wont give any results because it was raided by feds.

**Comment by shmizan** [comment]
@Jezze83 why are you spreading misinformation and FUD?
also there is a new domain available for filelist.

**Comment by elgatito** [comment]
I have fixed Filelist provider. But make sure to insert passkey to provider credentials.
