### ISSUE TITLE
Парсер burst не ищет на rutracker из-за символа '\x96' в таблице результатов. UnicodeDecodeError.

### ISSUE THREAD

**Issue by pavelmxx** [elgatito/script.elementum.burst#306]
Заканчивается ошибкой на таких поисковых запросах как "nobody 2021" и "the empire strikes back 1980", например.
А запросы "nobody" и "the empire strikes back" без указания года строят другую таблицу результатов и поиск не завершается ошибкой.
По факту длительного ожидания бывает, что не выдает результаты поискового запроса на других трекерах, и rutracker приходится вовсе отключать в настройках.

```
2021-10-28 03:40:02.478 T:10748  NOTICE: [script.elementum.burst] [rutracker] Login successful
2021-10-28 03:40:02.481 T:10748  NOTICE: [script.elementum.burst] [rutracker] >            RuTracker search URL: http://rutracker.lib/forum/tracker.php?nm=nobody+2021&prev_new=0&prev_oop=1&f[]=-1&o=10&s=2&oop=1&pn=
2021-10-28 03:40:03.017 T:10748 WARNING: [script.elementum.burst] Could not fix unicode string: UnicodeDecodeError('ascii', '\x96', 0, 1, 'ordinal not in range(128)')
2021-10-28 03:40:03.019 T:10748   ERROR: Exception in thread Thread-2:
                                            Traceback (most recent call last):
                                              File "C:\Kodi_portable\kodi\system\python\Lib\threading.py", line 801, in __bootstrap_inner
                                                self.run()
                                              File "C:\Kodi_portable\kodi\system\python\Lib\threading.py", line 754, in run
                                                self.__target(*self.__args, **self.__kwargs)
                                              File "C:\Kodi_portable\kodi\portable_data\addons\script.elementum.burst\burst\burst.py", line 645, in run_provider
                                                results = process(provider=provider, generator=extract_torrents, filtering=filterInstance, has_special=payload['has_special'], skip_auth=payload['skip_auth'], start_time=start_time, timeout=timeout)
                                              File "C:\Kodi_portable\kodi\portable_data\addons\script.elementum.burst\burst\provider.py", line 324, in process
                                                verify_size))
                                              File "C:\Kodi_portable\kodi\portable_data\addons\script.elementum.burst\burst\provider.py", line 49, in generate_payload
                                                if filtering.verify(provider, v_name, v_size):
                                              File "C:\Kodi_portable\kodi\portable_data\addons\script.elementum.burst\burst\filtering.py", line 540, in verify
                                                name = normalize_string(name)
                                              File "C:\Kodi_portable\kodi\portable_data\addons\script.elementum.burst\burst\normalize.py", line 189, in normalize_string
                                                string = unquote(string)
                                              File "C:\Kodi_portable\kodi\system\python\Lib\urllib.py", line 1234, in unquote
                                                bits = s.split('%')
                                            AttributeError: 'NoneType' object has no attribute 'split'
2021-10-28 03:41:38.379 T:11164 WARNING: [script.elementum.burst] RuTracker работают медленно
2021-10-28 03:41:38.385 T:11164  NOTICE: [script.elementum.burst] Providers returned 26 results in 117.22 seconds
2021-10-28 03:41:38.392 T:9052  NOTICE: [plugin.video.elementum] [GIN] 2021/10/28 - 03:41:38 | 200 |            0s |       127.0.0.1 | POST     "/callbacks/1512322189038895962"
2021-10-28 03:41:39.053 T:9052  NOTICE: [plugin.video.elementum] INFO  linkssearch   processLinks     Received 26 unique links.
```

```
2021-10-28 04:30:04.347 T:10168  NOTICE: [plugin.video.elementum] DEBU  proxy        ? dumpResponse     [19] <-- 200 http://rutracker.lib/forum/index.php
2021-10-28 04:30:04.396 T:10168  NOTICE: [plugin.video.elementum] DEBU  proxy        ? dumpResponse     RESPONSE:
2021-10-28 04:30:04.396 T:10168  NOTICE: [plugin.video.elementum] HTTP/1.1 200 OK
2021-10-28 04:30:04.396 T:10168  NOTICE: [plugin.video.elementum] Transfer-Encoding: chunked
2021-10-28 04:30:04.396 T:10168  NOTICE: [plugin.video.elementum] Connection: keep-alive
2021-10-28 04:30:04.396 T:10168  NOTICE: [plugin.video.elementum] Content-Security-Policy: frame-ancestors 'self'
2021-10-28 04:30:04.396 T:10168  NOTICE: [plugin.video.elementum] Content-Type: text/html; charset=Windows-1251
2021-10-28 04:30:04.396 T:10168  NOTICE: [plugin.video.elementum] Date: Thu, 28 Oct 2021 01:30:00 GMT
2021-10-28 04:30:04.397 T:10168  NOTICE: [plugin.video.elementum] Referrer-Policy: same-origin
2021-10-28 04:30:04.397 T:10168  NOTICE: [plugin.video.elementum] Server: nginx
2021-10-28 04:30:04.397 T:10168  NOTICE: [plugin.video.elementum] Vary: Accept-Encoding
2021-10-28 04:30:04.397 T:10168  NOTICE: [plugin.video.elementum] X-Bb-Id: rto
2021-10-28 04:30:04.397 T:10168  NOTICE: [plugin.video.elementum] X-Frame-Options: SAMEORIGIN
2021-10-28 04:30:04.397 T:10168  NOTICE: [plugin.video.elementum]
2021-10-28 04:30:04.397 T:10168  NOTICE: [plugin.video.elementum] 19271
2021-10-28 04:30:04.397 T:10168  NOTICE: [plugin.video.elementum] <!DOCTYPE html>
2021-10-28 04:30:04.397 T:10168  NOTICE: [plugin.video.elementum] <html lang="ru">
2021-10-28 04:30:04.397 T:10168  NOTICE: [plugin.video.elementum] <head>
2021-10-28 04:30:04.397 T:10168  NOTICE: [plugin.video.elementum]
2021-10-28 04:30:04.397 T:10168  NOTICE: [plugin.video.elementum] <meta charset="Windows-1251">
2021-10-28 04:30:04.398 T:10168   ERROR: [plugin.video.elementum] Traceback (most recent call last):
2021-10-28 04:30:04.398 T:10168   ERROR: [plugin.video.elementum]   File "C:\Kodi_portable\kodi\portable_data\addons\plugin.video.elementum\resources\site-packages\elementum\daemon.py", line 322, in elementumd_thread
2021-10-28 04:30:04.398 T:10168   ERROR: [plugin.video.elementum]     log.info(toUtf8(proc.stdout.readline().rstrip()))
2021-10-28 04:30:04.398 T:10168   ERROR: [plugin.video.elementum]   File "C:\Kodi_portable\kodi\portable_data\addons\plugin.video.elementum\resources\site-packages\elementum\util.py", line 75, in toUtf8
2021-10-28 04:30:04.398 T:10168   ERROR: [plugin.video.elementum]     string = string.decode("utf-8")
2021-10-28 04:30:04.398 T:10168   ERROR: [plugin.video.elementum]   File "C:\Kodi_portable\kodi\system\python\Lib\encodings\utf_8.py", line 16, in decode
2021-10-28 04:30:04.399 T:10168   ERROR: [plugin.video.elementum]     return codecs.utf_8_decode(input, errors, True)
2021-10-28 04:30:04.399 T:10168   ERROR: [plugin.video.elementum] UnicodeDecodeError: 'utf8' codec can't decode byte 0xca in position 34: invalid continuation byte
2021-10-28 04:30:04.399 T:10168   ERROR: [plugin.video.elementum]
2021-10-28 04:30:04.399 T:10168   ERROR: Exception in thread Thread-2:
                                            Traceback (most recent call last):
                                              File "C:\Kodi_portable\kodi\system\python\Lib\threading.py", line 801, in __bootstrap_inner
                                                self.run()
                                              File "C:\Kodi_portable\kodi\system\python\Lib\threading.py", line 754, in run
                                                self.__target(*self.__args, **self.__kwargs)
                                              File "C:\Kodi_portable\kodi\portable_data\addons\plugin.video.elementum\resources\site-packages\elementum\daemon.py", line 322, in elementumd_thread
                                                log.info(toUtf8(proc.stdout.readline().rstrip()))
                                              File "C:\Kodi_portable\kodi\portable_data\addons\plugin.video.elementum\resources\site-packages\elementum\util.py", line 75, in toUtf8
                                                string = string.decode("utf-8")
                                              File "C:\Kodi_portable\kodi\system\python\Lib\encodings\utf_8.py", line 16, in decode
                                                return codecs.utf_8_decode(input, errors, True)
                                            UnicodeDecodeError: 'utf8' codec can't decode byte 0xca in position 34: invalid continuation byte
2021-10-28 04:32:01.062 T:11096 WARNING: [script.elementum.burst] NNM-Club, RuTracker, Кинозал, Rustorka работают медленно
2021-10-28 04:32:01.063 T:11096  NOTICE: [script.elementum.burst] Providers returned 0 results in 117.04 seconds
```

```
2021-10-28 06:21:50.199 T:11432   DEBUG: [script.elementum.burst] [rutracker] [tr24][of][ldr] solomun - nobody is not loved - 2021 (electronic | house) *** Missing release type keyword
2021-10-28 06:21:50.202 T:11432   DEBUG: [script.elementum.burst] [rutracker] (score) никто / nobody (by david buckley) - 2021, mp3 (tracks), 320 kbps *** Resolution not allowed (filter_music)
2021-10-28 06:21:50.203 T:11432   DEBUG: [script.elementum.burst] [rutracker]          [tr24][of] jazzparty - nobody gets away - 2021 (blues | jazz) *** Missing release type keyword
2021-10-28 06:21:50.204 T:11432   DEBUG: [script.elementum.burst] [rutracker] (blues | rock) [web] caleb petty - mr. nobody - 2021, flac (tracks), lossless *** Resolution not allowed (filter_music)
2021-10-28 06:21:50.205 T:11432   DEBUG: [script.elementum.burst] [rutracker] (pop) [stream] zayn - nobody is listening - 2021, flac (tracks), lossless *** Resolution not allowed (filter_music)
2021-10-28 06:21:50.205 T:11432   DEBUG: [script.elementum.burst] [rutracker]            (blues/rock) caleb petty - mr. nobody - 2021, mp3, 320 kbps *** Resolution not allowed (filter_music)
2021-10-28 06:21:50.206 T:11432   DEBUG: [script.elementum.burst] [rutracker] (country, americana, folk, pop) nobody's girl - nobody's girl - 2021, mp3, 320 kbps *** Resolution not allowed (filter_music)
2021-10-28 06:21:50.207 T:11432   DEBUG: [script.elementum.burst] [rutracker]              [tr24][of] nobody's girl - nobody's girl - 2021 (country) *** Missing release type keyword
2021-10-28 06:21:50.208 T:11432   DEBUG: [script.elementum.burst] [rutracker]                 (pop) zayn - nobody is listening - 2021, mp3, 320 kbps *** Resolution not allowed (filter_music)
2021-10-28 06:21:50.209 T:11432   DEBUG: [script.elementum.burst] [rutracker]       [tr24][of] betty bennett - nobody else but me - 2009/2021 (jazz) *** Missing release type keyword
2021-10-28 06:21:50.219 T:11432 WARNING: [script.elementum.burst] Could not fix unicode string: UnicodeDecodeError('ascii', '\x96', 0, 1, 'ordinal not in range(128)')
2021-10-28 06:21:50.219 T:11432   DEBUG: [script.elementum.burst] Traceback (most recent call last):
2021-10-28 06:21:50.219 T:11432   DEBUG: [script.elementum.burst]   File "C:\Kodi_portable\kodi\portable_data\addons\script.elementum.burst\burst\normalize.py", line 292, in fix_bad_unicode
2021-10-28 06:21:50.219 T:11432   DEBUG: [script.elementum.burst]     tried_fixing = reinterpret_windows1252_as_utf8(string)
2021-10-28 06:21:50.219 T:11432   DEBUG: [script.elementum.burst]   File "C:\Kodi_portable\kodi\portable_data\addons\script.elementum.burst\burst\normalize.py", line 335, in reinterpret_windows1252_as_utf8
2021-10-28 06:21:50.220 T:11432   DEBUG: [script.elementum.burst]     return py2_decode(''.join(altered_bytes), 'utf-8', 'replace')
2021-10-28 06:21:50.220 T:11432   DEBUG: [script.elementum.burst] UnicodeDecodeError: 'ascii' codec can't decode byte 0x96 in position 0: ordinal not in range(128)
2021-10-28 06:21:50.220 T:11432   DEBUG: [script.elementum.burst]
2021-10-28 06:21:50.221 T:11432   ERROR: Exception in thread Thread-2:
                                            Traceback (most recent call last):
                                              File "C:\Kodi_portable\kodi\system\python\Lib\threading.py", line 801, in __bootstrap_inner
                                                self.run()
                                              File "C:\Kodi_portable\kodi\system\python\Lib\threading.py", line 754, in run
                                                self.__target(*self.__args, **self.__kwargs)
                                              File "C:\Kodi_portable\kodi\portable_data\addons\script.elementum.burst\burst\burst.py", line 645, in run_provider
                                                results = process(provider=provider, generator=extract_torrents, filtering=filterInstance, has_special=payload['has_special'], skip_auth=payload['skip_auth'], start_time=start_time, timeout=timeout)
                                              File "C:\Kodi_portable\kodi\portable_data\addons\script.elementum.burst\burst\provider.py", line 324, in process
                                                verify_size))
                                              File "C:\Kodi_portable\kodi\portable_data\addons\script.elementum.burst\burst\provider.py", line 49, in generate_payload
                                                if filtering.verify(provider, v_name, v_size):
                                              File "C:\Kodi_portable\kodi\portable_data\addons\script.elementum.burst\burst\filtering.py", line 540, in verify
                                                name = normalize_string(name)
                                              File "C:\Kodi_portable\kodi\portable_data\addons\script.elementum.burst\burst\normalize.py", line 189, in normalize_string
                                                string = unquote(string)
                                              File "C:\Kodi_portable\kodi\system\python\Lib\urllib.py", line 1234, in unquote
                                                bits = s.split('%')
                                            AttributeError: 'NoneType' object has no attribute 'split'
```

**Comment by elgatito** [comment]
@pavelmxx @antonsoroko Не могу это воспроизвести на последнем Коди.

**Comment by elgatito** [comment]
Closing. Can't determine it is still an issue.
