### ISSUE TITLE
ValueError: invalid literal for int() with base 10: ''

### ISSUE THREAD

**Issue by rvanginneken** [elgatito/script.elementum.burst#52]
Having an Elementum Burst Error, I found In my kodi logs the following:

```
11:15:35.265 T:1413477120  NOTICE: [script.elementum.burst] Python version: ['2.7.13 (default, Nov 24 2017, 17:33:09) ', '[GCC 6.3.0 20170516]']
                                                dist: ('debian', '9.4', '')
                                                linux_distribution: ('debian', '9.4', '')
                                                system: Linux
                                                machine: armv7l
                                                platform: Linux-4.14.34-2-osmc-armv7l-with-debian-9.4
                                                uname: ('Linux', 'osmc_main', '4.14.34-2-osmc', '#1 SMP PREEMPT Thu Jun 7 18:43:25 UTC 2018', 'armv7l', '')
                                                version: #1 SMP PREEMPT Thu Jun 7 18:43:25 UTC 2018
                                                mac_ver: ('', ('', '', ''), '')
11:15:35.268 T:1413477120   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: invalid literal for int() with base 10: ''
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/script.elementum.burst/burst.py", line 7, in <module>
                                                from burst.burst import search
                                              File "/home/osmc/.kodi/addons/script.elementum.burst/burst/burst.py", line 15, in <module>
                                                from elementum.provider import append_headers, get_setting, set_setting, log
                                              File "/home/osmc/.kodi/addons/plugin.video.elementum/resources/site-packages/elementum/provider.py", line 8, in <module>
                                                from elementum.config import ELEMENTUMD_HOST
                                              File "/home/osmc/.kodi/addons/plugin.video.elementum/resources/site-packages/elementum/config.py", line 14, in <module>
                                                init()
                                              File "/home/osmc/.kodi/addons/plugin.video.elementum/resources/site-packages/elementum/config.py", line 11, in init
                                                JSONRPC_EXT_PORT = int(ADDON.getSetting("local_port"))
                                            ValueError: invalid literal for int() with base 10: ''
                                            -->End of Python script error report<--
11:15:43.525 T:1925564928   ERROR: CPythonInvoker(42, /home/osmc/.kodi/addons/plugin.video.elementum/navigation.py): script didn't stop in 5 seconds - let's kill it

```

**Comment by elgatito** [comment]
Restart Kodi after plugin.video.elementum updated to 0.0.50.

**Comment by rvanginneken** [comment]
@elgatito According to my add-ons
elementum: 0.0.50
burst: 0.0.17
repository: 0.0.50

**Comment by elgatito** [comment]
1) restart Kodi
2) if still reproduced - open Elementum settings, press OK (save them).
3) if reproduced - restart Kodi

**Comment by rvanginneken** [comment]
@elgatito Tried your steps, sadly it still occurs.
Can I share any other logs that could help?

**Comment by elgatito** [comment]
Check the last tab in Elementum settings. 
Values there should be:
local_port=65221
remote_host=127.0.0.1
remote_port=65220

If you have these values - open http://192.168.0.1:65220/debug/bundle  (replace with device IP), it will download debug information.

**Comment by rvanginneken** [comment]
[Uploading bundle_2018_6_20_10_14.log…]

**Comment by rvanginneken** [comment]
[bundle_2018_6_20_10_14.log](https://github.com/elgatito/script.elementum.burst/files/2118832/bundle_2018_6_20_10_14.log)

**Comment by mymo1982** [comment]
Very same issue as @rvanginneken here

**Comment by elgatito** [comment]
It is fixed in elementum 0.0.51. Try to update.

**Comment by rvanginneken** [comment]
@elgatito Thanks for your quick response!
I should be able to update through kodi right?

**Comment by rvanginneken** [comment]
For those wondering the same thing: yes, Elementum is automatically updated on the kodi.
@elgatito Thanks again, great addon !!
