### ISSUE TITLE
Cannot find any torrents, KeyError: 'proxyUrl'

### ISSUE THREAD

**Issue by regalstreak** [elgatito/script.elementum.burst#66]
I'm not using any proxy, idk what's the problem with this. Would be glad if you could help me on this

```
22:04:52.813 T:140032568452864   DEBUG: [script.elementum.burst] Opening URL: 'https://thepiratebay.org/search/suits%20s07e14/0/99/200'
22:04:52.813 T:140032576845568   DEBUG: [script.elementum.burst] --- limetorrents using POST payload: {}
22:04:52.815 T:140032551667456   DEBUG: [script.elementum.burst] Cookies for 'https://www.torlock2.com/television/torrents/suits-s07e14.html': <LWPCookieJar[]>
22:04:52.815 T:140032576845568   DEBUG: [script.elementum.burst] ----limetorrents filtering with post_data: {}
22:04:52.816 T:140032653842176   DEBUG: [script.elementum.burst] [kickass] Translated titles from Elementum: {u'en': u'suits', u'cn': u'\u8bc9\u8bbc\u53cc\u96c4', u'jp': u'suits \u30b9\u30fc\u30c4', u'it': u'suite', u'source': u'Suits', u'br': u'homens de terno', u'ua': u'\u043a\u043e\u0441\u0442\u044e\u043c\u0438', u'original': u'suits'}
22:04:52.817 T:140032568452864   DEBUG: [script.elementum.burst] Cookies for 'https://thepiratebay.org/search/suits%20s07e14/0/99/200': <LWPCookieJar[]>
22:04:52.818 T:140032551667456   DEBUG: [script.elementum.burst] Setting opener handlers: [<urllib2.HTTPCookieProcessor instance at 0x7f5c161c7ef0>]
22:04:52.819 T:140032653842176   DEBUG: [script.elementum.burst] [kickass] After keywords  - Query: u'suits s07e14' - Extra: ''
22:04:52.819 T:140032560060160   DEBUG: [script.elementum.burst] Cookies for 'http://www.magnetdl.com/s/suits-s07e14/': <LWPCookieJar[]>
22:04:52.820 T:140032576845568  NOTICE: [script.elementum.burst] >         LimeTorrents search URL: https://www.limetorrents.io/search/all/suits%20s07e14/seeds/1/
22:04:52.820 T:140032568452864   DEBUG: [script.elementum.burst] Setting opener handlers: [<urllib2.HTTPCookieProcessor instance at 0x7f5c161c7f38>]
22:04:52.821 T:140032560060160   DEBUG: [script.elementum.burst] Setting opener handlers: [<urllib2.HTTPCookieProcessor instance at 0x7f5c153e27a0>]
22:04:52.822 T:140032653842176   DEBUG: [script.elementum.burst] -   kickass query: u'suits s07e14'
22:04:52.822 T:140032576845568   DEBUG: [script.elementum.burst] Opening URL: 'https://www.limetorrents.io/search/all/suits%20s07e14/seeds/1/'
22:04:52.822 T:140032653842176   DEBUG: [script.elementum.burst] --  kickass url_search before token: u'https://katcr.co/usearch/suits%20s07e14%20category:tv/?field=seeders&sorder=desc&suits%20s07e14'
22:04:52.823 T:140032653842176   DEBUG: [script.elementum.burst] --- kickass using POST payload: {}
22:04:52.823 T:140032576845568   DEBUG: [script.elementum.burst] Cookies for 'https://www.limetorrents.io/search/all/suits%20s07e14/seeds/1/': <LWPCookieJar[]>
22:04:52.823 T:140032653842176   DEBUG: [script.elementum.burst] ----kickass filtering with post_data: {}
22:04:52.823 T:140032576845568   DEBUG: [script.elementum.burst] Setting opener handlers: [<urllib2.HTTPCookieProcessor instance at 0x7f5c15402d40>]
22:04:52.824 T:140032653842176  NOTICE: [script.elementum.burst] >              KickAss search URL: https://katcr.co/usearch/suits%20s07e14%20category:tv/?field=seeders&sorder=desc&suits%20s07e14
22:04:52.824 T:140032653842176   DEBUG: [script.elementum.burst] Opening URL: 'https://katcr.co/usearch/suits%20s07e14%20category:tv/?field=seeders&sorder=desc&suits%20s07e14'
22:04:52.825 T:140032653842176   DEBUG: [script.elementum.burst] Cookies for 'https://katcr.co/usearch/suits%20s07e14%20category:tv/?field=seeders&sorder=desc&suits%20s07e14': <LWPCookieJar[]>
22:04:52.825 T:140032653842176   DEBUG: [script.elementum.burst] Setting opener handlers: [<urllib2.HTTPCookieProcessor instance at 0x7f5c1540f128>]
22:04:52.826 T:140033759627008   ERROR: Exception in thread Thread-1:
                                            Traceback (most recent call last):
                                              File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
                                                self.run()
                                              File "/usr/lib/python2.7/threading.py", line 754, in run
                                                self.__target(*self.__args, **self.__kwargs)
                                              File "/home/regalstreak/.kodi/addons/script.elementum.burst/burst/burst.py", line 511, in run_provider
                                                results = process(provider=provider, generator=extract_from_api, filtering=filterInstance, has_special=payload['has_special'])
                                              File "/home/regalstreak/.kodi/addons/script.elementum.burst/burst/provider.py", line 162, in process
                                                client.open(token_url.encode('utf-8'), proxy_url=filtering.info['proxyUrl'], charset=definition['charset'])
                                            KeyError: 'proxyUrl'
22:04:52.845 T:140032670627584 WARNING: [script.elementum.burst] Status for 'https://www.torrentdownloads.me/search/?search=suits+s07e14' : error(104, 'Connection reset by peer')
22:04:52.846 T:140032670627584   DEBUG: [script.elementum.burst] Status for 'https://www.torrentdownloads.me/search/?search=suits+s07e14' : error(104, 'Connection reset by peer')
22:04:52.846 T:140032670627584   DEBUG: [script.elementum.burst] [torrentdownloads] Accepted resolutions: ['filter_480p', 'filter_720p', 'filter_1080p', 'filter_2k', 'filter_4k']
22:04:52.847 T:140032670627584   DEBUG: [script.elementum.burst] [torrentdownloads] Accepted release types: ['480p', u'480\u0440', 'xvid', 'dvd', 'dvdrip', 'hdtv', '720p', u'720\u0440', 'hdrip', 'bluray', 'blu_ray', 'brrip', 'bdrip', 'hdtv', '/hd720p', '1280x720', '1080p', u'1080\u0440', '1080i', 'fullhd', '_fhd_', '/hd1080p', '/hdr1080p', '1920x1080', '_2k_', '1440p', u'1440\u0440', u'_2\u043a_', '_4k_', '2160p', u'2160\u0440', '_uhd_', u'_4\u043a_', '_dvd_', 'dvdrip', 'dvd-rip', 'vcdrip', 'hdrip', 'hd-rip', 'hdtv', 'screener', '_scr_', 'webdl', 'webrip', 'web-rip', 'web_dl', 'dlrip', '_yts_', 'dvdscr', 'dvd-scr', 'brrip', 'bdrip', 'bd-rip', 'bluray', 'blu-ray', 'bdremux', 'bd-remux']
22:04:52.847 T:140032670627584   DEBUG: [script.elementum.burst] [torrentdownloads] Blocked release types: ['workprint', 'trailer', u'\u0442\u0440\u0435\u0439\u043b\u0435\u0440', u'\u0442\u0438\u0437\u0435\u0440', 'telesync', '_ts_', '_tc_', '_3d_', '_cam_', 'hdcam', 'vhsrip', '_tvrip', 'satrip']
22:04:52.847 T:140032670627584   DEBUG: [script.elementum.burst] [torrentdownloads] Minimum size: 0.0 GB
22:04:52.847 T:140032670627584   DEBUG: [script.elementum.burst] [torrentdownloads] Maximum size: 100.0 GB
22:04:52.848 T:140032670627584   DEBUG: [script.elementum.burst] Extracting torrents from torrentdownloads using definitions: {u'show_query': u'', u'season_keywords2': u'{title:original} s{season:2}', u'movie_extra': u'', u'color': u'FFB74F1A', u'parser': {u'peers': u"item(tag='span', order=2)", u'name': u"item('a')", u'seeds': u"item(tag='span', order=3)", u'row': u"find_all('div', ('class', 'grey_bar3'))", u'infohash': u'', u'torrent': u"item(tag='a', attribute='href')", u'size': u"item(tag='span', order=4)"}, u'private': False, u'tv_extra': u'', u'anime_query': u'', u'tv_extra2': u'', u'tv_keywords2': u'', u'general_query': u'', 'id': '', u'season_extra': u'', u'predefined': False, u'season_query': u'', u'tv_keywords': u'{title:original} s{season:2}e{episode:2}', 'alias': '', 'charset': 'utf8', u'base_url': u'https://www.torrentdownloads.me/search/?search=QUERYEXTRA', u'languages': u'en', u'anime_keywords': u'{title:original} {episode}', u'season_extra2': u'', u'anime_extra': u'', u'movie_keywords': u'{title:original} {year}', u'movie_query': u'', u'login_object': u'', 'root_url': u'https://www.torrentdownloads.me', u'subpage': True, u'general_keywords': u'{title:original}', u'name': u'TorrentDownloads', u'language': None, u'enabled': True, u'general_extra': u'', u'login_failed': u'', u'separator': u'+', u'login_path': None, u'season_keywords': u'{title:original} season {season:2}'}
22:04:52.848 T:140032670627584   DEBUG: [script.elementum.burst] >>>>>> torrentdownloads would send 0 torrents to Elementum <<<<<<<
22:04:52.849 T:140032670627584  NOTICE: [script.elementum.burst] >>    TorrentDownloads returned  0 results in 0.1 seconds
22:04:52.855 T:140032560060160   DEBUG: [script.elementum.burst] Decoding charset from utf-8-sig for 'http://www.magnetdl.com/s/suits-s07e14/'
22:04:52.856 T:140032560060160   DEBUG: [script.elementum.burst] Status for 'http://www.magnetdl.com/s/suits-s07e14/' : 200
22:04:52.856 T:140032560060160   DEBUG: [script.elementum.burst] [magnetdl] Accepted resolutions: ['filter_480p', 'filter_720p', 'filter_1080p', 'filter_2k',
```

**Comment by elgatito** [comment]
I will fix it, but you should update your Elementum to the latest version.

**Comment by regalstreak** [comment]
Hahaha thanks a lot man <3 I used to be soo frustrated because i wouldn't get results and now I'm being flooded with results! Thanks again for really listening to issues and fixing this. Kudos
