### ISSUE TITLE
Burst don't work on windows

### ISSUE THREAD

**Issue by Nemiroff** [elgatito/script.elementum.burst#67]
PySock need win_inet_pton
`00:38:08.752 T:6460   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: To run PySocks on Windows you must install win_inet_pton
                                            Traceback (most recent call last):
                                              File "C:\Kodi_portable\kodi\portable_data\addons\script.elementum.burst\burst.py", line 7, in <module>
                                                from burst.burst import search
                                              File "C:\Kodi_portable\kodi\portable_data\addons\script.elementum.burst\burst\burst.py", line 19, in <module>
                                                from provider import process
                                              File "C:\Kodi_portable\kodi\portable_data\addons\script.elementum.burst\burst\provider.py", line 13, in <module>
                                                from client import Client
                                              File "C:\Kodi_portable\kodi\portable_data\addons\script.elementum.burst\burst\client.py", line 16, in <module>
                                                import socks
                                              File "C:\Kodi_portable\kodi\portable_data\addons\script.elementum.burst\resources\site-packages\socks.py", line 80, in <module>
                                                "To run PySocks on Windows you must install win_inet_pton")
                                            ImportError: To run PySocks on Windows you must install win_inet_pton
                                            -->End of Python script error report<--`

**Comment by Nemiroff** [comment]
dublicate #63
