### ISSUE TITLE
RARBG timed out, Torrentleech login failed 0.0.21

### ISSUE THREAD

**Issue by ilanerukh** [elgatito/script.elementum.burst#70]
Here is a part of the log file.
RARBG is timed out, Torrentleech cloudhole enabled and the login fail.

`12:07:04.590 T:9308  NOTICE: [script.elementum.burst] Burstin' with RARBG, 1337x, YTS, The Pirate Bay, TorrentLeech, MagnetDL, TorLock
12:07:04.592 T:9308   ERROR: [script.elementum.burst] Getting CloudHole key error: AttributeError("'NoneType' object has no attribute 'open'",)
12:07:04.671 T:12788  NOTICE: [script.elementum.burst] >>                 YTS returned  0 results in 0.1 seconds
12:07:04.697 T:1860  NOTICE: [script.elementum.burst] [rarbg] Using translated 'original' title u'billions'
12:07:04.699 T:13920  NOTICE: [script.elementum.burst] [1337x] Using translated 'original' title u'billions'
12:07:04.700 T:7724  NOTICE: [script.elementum.burst] [thepiratebay] Using translated 'original' title u'billions'
12:07:04.701 T:7192  NOTICE: [script.elementum.burst] [torrentleech] Using translated 'original' title u'billions'
12:07:04.702 T:4744  NOTICE: [script.elementum.burst] [magnetdl] Using translated 'original' title u'billions'
12:07:04.703 T:7856  NOTICE: [script.elementum.burst] [torlock] Using translated 'original' title u'billions'
12:07:04.705 T:13920  NOTICE: [script.elementum.burst] >                1337x search URL: https://www.1337x.to/search/billions+s03e11/1/
12:07:04.707 T:7724  NOTICE: [script.elementum.burst] >       The Pirate Bay search URL: https://thepiratebay.org/search/billions%20s03e11/0/99/200
12:07:04.710 T:1860   ERROR: Exception in thread Thread-1:
                                            Traceback (most recent call last):
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\threading.py", line 801, in __bootstrap_inner
                                                self.run()
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\threading.py", line 754, in run
                                                self.__target(*self.__args, **self.__kwargs)
                                              File "C:\Users\ilane\AppData\Roaming\Kodi\addons\script.elementum.burst\burst\burst.py", line 511, in run_provider
                                                results = process(provider=provider, generator=extract_from_api, filtering=filterInstance, has_special=payload['has_special'])
                                              File "C:\Users\ilane\AppData\Roaming\Kodi\addons\script.elementum.burst\burst\provider.py", line 162, in process
                                                client.open(token_url.encode('utf-8'), proxy_url=filtering.info['proxyUrl'], charset=definition['charset'])
                                            KeyError: 'proxyUrl'
12:07:04.711 T:4744  NOTICE: [script.elementum.burst] >             MagnetDL search URL: http://www.magnetdl.com/b/billions-s03e11/
12:07:04.712 T:7856  NOTICE: [script.elementum.burst] >              TorLock search URL: https://www.torlock2.com/television/torrents/billions-s03e11.html
12:07:05.018 T:7192 WARNING: [script.elementum.burst] Status for 'https://classic.torrentleech.org/user/account/login/' : 503
12:07:05.018 T:7192 WARNING: [script.elementum.burst] CloudFlared at https://classic.torrentleech.org/user/account/login/, try enabling CloudHole
12:07:05.019 T:7192   ERROR: [script.elementum.burst] [torrentleech] Login failed: 503
12:07:05.019 T:7192  NOTICE: [script.elementum.burst] >>        TorrentLeech returned  0 results in 0.4 seconds
12:07:05.650 T:4744  NOTICE: [script.elementum.burst] >>            MagnetDL returned 18 results in 1.1 seconds
12:07:05.920 T:7856  NOTICE: [script.elementum.burst] >>             TorLock returned  0 results in 1.3 seconds
12:07:06.251 T:7724  NOTICE: [script.elementum.burst] [thepiratebay] Using translated 'original' title u'billions'
12:07:06.252 T:7724  NOTICE: [script.elementum.burst] >       The Pirate Bay search URL: https://thepiratebay.org/search/billions%20s03/0/99/200
12:07:06.841 T:13920  NOTICE: [script.elementum.burst] >>               1337x returned 14 results in 2.3 seconds
12:07:07.738 T:7724  NOTICE: [script.elementum.burst] >>      The Pirate Bay returned 20 results in 3.1 seconds
12:07:12.825 T:2060  NOTICE: [plugin.video.elementum] ERRO  tmdb         ▶ func1            Bad status getting season 22 of show 2190: 404
12:07:13.037 T:2060  NOTICE: [plugin.video.elementum] ERRO  tmdb         ▶ func1            Bad status getting S22E01 of 2190: 404
12:07:14.705 T:2060  NOTICE: [plugin.video.elementum] [GIN] 2018/08/04 - 12:07:14 | 200 |    2.3089981s |       127.0.0.1 | GET      /shows/trakt/progress
12:07:17.755 T:9308 WARNING: [script.elementum.burst] RARBGעבר הזמן
12:07:17.768 T:9308  NOTICE: [script.elementum.burst] Providers returned 30 results in 13.18 seconds
12:07:17.770 T:2060  NOTICE: [plugin.video.elementum] [GIN] 2018/08/04 - 12:07:17 | 200 |            0s |       127.0.0.1 | POST     /callbacks/203101283895217702
12:07:17.848 T:2060  NOTICE: [plugin.video.elementum] INFO  linkssearch  ▶ processLinks     Received 30 unique links.`

**Comment by elgatito** [comment]
Try version 0.0.22.

**Comment by Sandbird** [comment]
The cloudhole bug for TorrentLeech i think is fixed now, but it still wont login to the site.
`[script.elementum.burst] [torrentleech] Login failed: 503`
, although everything seems to be corrent. 
Even tried adding the 'login': 'submit' 
`"login_object": "{'username': USERNAME, 'password': PASSWORD, 'login': 'submit'}",`
but that didnt help

**Comment by elgatito** [comment]
Error 503 means page is protected with cloudhole and that is not working. They are changing the way to protect pages all the time. 
I will not do anything with that. Maybe someone will submit a change, then  Iwill review it.

**Comment by martinstz** [comment]
Hi!
On RARBG have a results from search when i test the search link, but not return results on addon.
Example:

RARBG search URL: https://torrentapi.org/pubapi_v2.php?mode=search&search_string=wonder%202017&category=14;48;17;44;45;47;50;51;52;42;46&format=json_extended&app_id=script.elementum.burst&token=bcp5z47vl9

RARBG returned  0 results in 0.7 seconds

Can you check this?

Thank you in advance!

**Comment by elgatito** [comment]
> Can you check this?

Full log file needed.

**Comment by martinstz** [comment]
Hmm... Now return results... Interesting!
Sorry!
Thank you!

**Comment by elgatito** [comment]
Please, check Burst 0.0.31 with Elementum >= 0.0.67.

**Comment by MilePule** [comment]
Elementum burst: rarbg,1337x timed out, no links were found.

**Comment by elgatito** [comment]
@MilePule if you want any help - you have to post log files.

**Comment by MilePule** [comment]
Oh sorry,
https://paste.ubuntu.com/p/R2pJFMNZ8J/

**Comment by elgatito** [comment]
@MilePule 
I have tried and both work well. 
You can try to increase providers timeout in Elementum.

**Comment by MilePule** [comment]
Already tried it, no go. I reverted to previous versions of elementum&burst and everything just works fine.

> @MilePule
> I have tried and both work well.
> You can try to increase providers timeout in Elementum.

Already tried it, no go. I reverted to previous versions of elementum&burst and everything just works fine.

**Comment by elgatito** [comment]
Can you show the log with previous elementum?

**Comment by MilePule** [comment]
I will soon, I just went out.

**Comment by MilePule** [comment]
> Can you show the log with previous elementum?

https://paste.ubuntu.com/p/Y5B8BGF9WG/

**Comment by martinstz** [comment]
Disable in Elementum Settings -> Proxy -> "Enable built in http proxy" and everything works fine!
