### ISSUE TITLE
not working on libreelec

### ISSUE THREAD

**Issue by tarasian666** [elgatito/script.elementum.burst#72]
ImportError: No module named urllib3

**Comment by elgatito** [comment]
Log?

**Comment by tarasian666** [comment]
17:45:56.522 T:3890221984   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named urllib3
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/script.elementum.burst/burst.py", line 7, in <module>
                                                from burst.burst import search
                                              File "/storage/.kodi/addons/script.elementum.burst/burst/burst.py", line 19, in <module>
                                                from provider import process
                                              File "/storage/.kodi/addons/script.elementum.burst/burst/provider.py", line 13, in <module>
                                                from client import Client
                                              File "/storage/.kodi/addons/script.elementum.burst/burst/client.py", line 9, in <module>
                                                import urllib3
                                            ImportError: No module named urllib3
                                            -->End of Python script error report<--

**Comment by elgatito** [comment]
Please, try 0.0.24.
