### ISSUE TITLE
Burst stopped working after updating to version 0.0.23 

### ISSUE THREAD

**Issue by valentiniljaz** [elgatito/script.elementum.burst#73]
Version 0.0.23 is using request package which requires certifi package which is not available. Below is the error report:

```
EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named certifi
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/script.elementum.burst/burst.py", line 7, in <module>
                                                from burst.burst import search
                                              File "/home/osmc/.kodi/addons/script.elementum.burst/burst/burst.py", line 19, in <module>
                                                from provider import process
                                              File "/home/osmc/.kodi/addons/script.elementum.burst/burst/provider.py", line 13, in <module>
                                                from client import Client
                                              File "/home/osmc/.kodi/addons/script.elementum.burst/burst/client.py", line 12, in <module>
                                                import requests
                                              File "/home/osmc/.kodi/addons/script.elementum.burst/resources/site-packages/requests/__init__.py", line 112, in <module>
                                                from . import utils
                                              File "/home/osmc/.kodi/addons/script.elementum.burst/resources/site-packages/requests/utils.py", line 24, in <module>
                                                from . import certs
                                              File "/home/osmc/.kodi/addons/script.elementum.burst/resources/site-packages/requests/certs.py", line 15, in <module>
                                                from certifi import where
                                            ImportError: No module named certifi
                                            -->End of Python script error report<--
```

**Comment by elgatito** [comment]
Please, try 0.0.24.

**Comment by valentiniljaz** [comment]
Yeah, it works. Thanks for quick response and fix.
